# oculuz/configuration/data_preprocessing_config.yaml

# Параметры нормализации RSSI
rssi:
  min_val: -130.0  # Минимальное истинное значение RSSI
  max_val: -30.0   # Максимальное истинное значение RSSI

# Параметры кодирования координат
coordinate:
  embedding_dim: 64  # Размерность эмбеддинга для каждой координаты (должно быть четным числом)
                     # Общая размерность для пары (lat, lon) будет 2 * embedding_dim, если их конкатенировать,
                     # или embedding_dim, если используется совместное кодирование.
                     # В данном случае, мы будем создавать отдельные эмбеддинги для lat и lon,
                     # которые затем могут быть конкатенированы или использованы отдельно.